# Generated by Django 3.0.5 on 2020-07-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.IntegerField(choices=[(0, 'Veg'), (1, 'Non Veg')]),
        ),
    ]
