# Generated by Django 3.0.5 on 2020-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200727_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('V', 'Veg'), ('NV', 'Non Veg')], max_length=2),
        ),
    ]
