# Generated by Django 3.0 on 2020-08-09 14:21

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200727_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='process',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
